# Use debian based image for Jekyll to run properly.
FROM ruby:3.2.2-bookworm

# Add required system packages.
#RUN apk add --no-cache build-base tzdata nodejs yarn sqlite-dev postgresql-dev mysql-dev git nano npm make
RUN apt-get update && apt-get install -y nano git make npm && apt-get clean

# Install global Node packages (npm install -g). These will be baked into this image and available at all times. Requires new image build when you want to update a package. Otherwise, use local installs.
#RUN npm install -g @mermaid-js/mermaid-cli

# Add user and configure directory.
#RUN adduser --disabled-password jekyll
#USER jekyll
WORKDIR /app

# Install gems.
#ENV GEM_HOME=/home/jekyll/gems PATH="/home/jekyll/gems/bin:$PATH"
RUN gem install jekyll:4.3.2 bundler:2.4.22

# Install local Node packages (npm install). (These would be put into /app and therefore not persisted if we mount our app there during development)
#RUN npm install @mermaid-js/mermaid-cli
ENV PATH="/app/node_modules/.bin:$PATH"

CMD ["/bin/bash"]